export const personnages = [
  {
    id: 0,
    nom: "Albert Einstein",
    indice_1: "Personnalité",
    indice_2: "Théorie de la relativité",
    indice_3: "Physicien",
    indice_4: "Prix Nobel",
    indice_5: "Moustache",
  },
  {
    id: 1,
    nom: "Tour Eiffel",
    indice_1: "Objet",
    indice_2: "Paris",
    indice_3: "Haute",
    indice_4: "Fer",
    indice_5: "Monument",
  },
  {
    id: 2,
    nom: "Tintin",
    indice_1: "Personnage de BD",
    indice_2: "Journaliste",
    indice_3: "Milou",
    indice_4: "Capitaine Haddock",
    indice_5: "Créé par Hergé",
  },
  {
    id: 3,
    nom: "Beyoncé",
    indice_1: "Chanteuse",
    indice_2: "Destiny's Child",
    indice_3: "Formation",
    indice_4: "Lemonade",
    indice_5: "Single Ladies",
  },
  {
    id: 4,
    nom: "Mona Lisa",
    indice_1: "Œuvre d'Art",
    indice_2: "Leonardo da Vinci",
    indice_3: "Sourire énigmatique",
    indice_4: "Louvre",
    indice_5: "Tableau",
  },
  {
    id: 5,
    nom: "Iron Man",
    indice_1: "Personnage de Fiction",
    indice_2: "Marvel",
    indice_3: "Tony Stark",
    indice_4: "Armure",
    indice_5: "Avengers",
  },
  {
    id: 6,
    nom: "Mozart",
    indice_1: "Compositeur",
    indice_2: "Classique",
    indice_3: "Piano",
    indice_4: "Symphonies",
    indice_5: "Requiem",
  },
  {
    id: 7,
    nom: "Harry Potter",
    indice_1: "Personnage de Livre",
    indice_2: "Poudlard",
    indice_3: "Magie",
    indice_4: "JK Rowling",
    indice_5: "Château",
  },
  {
    id: 8,
    nom: "La Joconde",
    indice_1: "Œuvre d'Art",
    indice_2: "Leonardo da Vinci",
    indice_3: "Sourire célèbre",
    indice_4: "Musée du Louvre",
    indice_5: "Tableau",
  },
  {
    id: 9,
    nom: "Elvis Presley",
    indice_1: "Chanteur",
    indice_2: "King of Rock and Roll",
    indice_3: "Hanches qui bougent",
    indice_4: "Graceland",
    indice_5: "Blue Suede Shoes",
  },
  {
    id: 10,
    nom: "Spider-Man",
    indice_1: "Personnage de Fiction",
    indice_2: "Marvel",
    indice_3: "Peter Parker",
    indice_4: "Toiles d'araignée",
    indice_5: "Super-héros",
  },
  {
    id: 11,
    nom: "Vincent van Gogh",
    indice_1: "Artiste",
    indice_2: "Nuit étoilée",
    indice_3: "Coupe d'oreille",
    indice_4: "Peintre post-impressionniste",
    indice_5: "Sunflowers",
  },
  {
    id: 12,
    nom: "Wonder Woman",
    indice_1: "Personnage de Fiction",
    indice_2: "DC Comics",
    indice_3: "Diana Prince",
    indice_4: "Lasso de vérité",
    indice_5: "Amazone",
  },
  {
    id: 13,
    nom: "Marie Curie",
    indice_1: "Personnalité",
    indice_2: "Deux fois lauréate du prix Nobel",
    indice_3: "Physicienne et chimiste",
    indice_4: "Radiographie",
    indice_5: "Radium",
  },
  {
    id: 14,
    nom: "Pikachu",
    indice_1: "Personnage de Fiction",
    indice_2: "Pokémon",
    indice_3: "Électrique",
    indice_4: "Jaune",
    indice_5: "Ash Ketchum",
  },
  {
    id: 15,
    nom: "Leonardo DiCaprio",
    indice_1: "Personnalité",
    indice_2: "Acteur",
    indice_3: "Oscar pour The Revenant",
    indice_4: "Titanic",
    indice_5: "Inception",
  },
  {
    id: 16,
    nom: "The Beatles",
    indice_1: "Groupe",
    indice_2: "Légendes du rock",
    indice_3: "John, Paul, George, Ringo",
    indice_4: "Abbey Road",
    indice_5: "Yellow Submarine",
  },
  {
    id: 17,
    nom: "Sherlock Holmes",
    indice_1: "Personnage de Livre",
    indice_2: "Détective",
    indice_3: "Arthur Conan Doyle",
    indice_4: "Pipe et Deerstalker",
    indice_5: "221B Baker Street",
  },
  {
    id: 18,
    nom: "Frida Kahlo",
    indice_1: "Artiste",
    indice_2: "Autoportraits",
    indice_3: "Mexicaine",
    indice_4: "Suribachi",
    indice_5: "Diego Rivera",
  },
  {
    id: 19,
    nom: "Eiffel 65",
    indice_1: "Groupe",
    indice_2: "Blue (Da Ba Dee)",
    indice_3: "Dance-pop",
    indice_4: "Italien",
    indice_5: "1990s",
  },
  {
    id: 20,
    nom: "James Bond",
    indice_1: "Personnage de Fiction",
    indice_2: "Agent secret",
    indice_3: "007",
    indice_4: "Aston Martin",
    indice_5: "Ian Fleming",
  },
  {
    id: 21,
    nom: "Marilyn Monroe",
    indice_1: "Personnalité",
    indice_2: "Actrice",
    indice_3: "Blonde emblématique",
    indice_4: "Robe blanche",
    indice_5: "Happy Birthday, Mr. President",
  },
  {
    id: 22,
    nom: "The Simpsons",
    indice_1: "Série TV",
    indice_2: "Springfield",
    indice_3: "Homer, Marge, Bart, Lisa, Maggie",
    indice_4: "Matt Groening",
    indice_5: "Donuts",
  },
  {
    id: 23,
    nom: "Coco Chanel",
    indice_1: "Personnalité",
    indice_2: "Mode",
    indice_3: "Little Black Dress",
    indice_4: "Parfum Chanel No. 5",
    indice_5: "Haute couture",
  },
  {
    id: 24,
    nom: "Dora l'Exploratrice",
    indice_1: "Personnage de TV",
    indice_2: "Enfant exploratrice",
    indice_3: "Sac à dos",
    indice_4: "Chaussette rouge",
    indice_5: "Chanson 'We Did It!'",
  },
  {
    id: 25,
    nom: "David Bowie",
    indice_1: "Artiste",
    indice_2: "Ziggy Stardust",
    indice_3: "Space Oddity",
    indice_4: "Chanteur caméléon",
    indice_5: "Rock",
  },
  {
    id: 26,
    nom: "Batman",
    indice_1: "Personnage de Fiction",
    indice_2: "DC Comics",
    indice_3: "Bruce Wayne",
    indice_4: "Bat-Signal",
    indice_5: "Gotham City",
  },
  {
    id: 27,
    nom: "Amélie Poulain",
    indice_1: "Personnage de Film",
    indice_2: "Le Fabuleux Destin d'Amélie Poulain",
    indice_3: "Montmartre",
    indice_4: "Nain de jardin",
    indice_5: "Raphaël",
  },
  {
    id: 28,
    nom: "Beethoven",
    indice_1: "Compositeur",
    indice_2: "Symphonie n°9",
    indice_3: "Sourd",
    indice_4: "Ludwig van",
    indice_5: "Classique",
  },
  {
    id: 29,
    nom: "Queen",
    indice_1: "Groupe",
    indice_2: "Freddie Mercury",
    indice_3: "Bohemian Rhapsody",
    indice_4: "We Will Rock You",
    indice_5: "Legendary",
  },
  {
    id: 30,
    nom: "Marlon Brando",
    indice_1: "Acteur",
    indice_2: "Le Parrain",
    indice_3: "Stella!",
    indice_4: "Méthode",
    indice_5: "Oscar",
  },
  {
    id: 31,
    nom: "The Little Mermaid",
    indice_1: "Film d'Animation",
    indice_2: "Ariel",
    indice_3: "Under the Sea",
    indice_4: "Disney",
    indice_5: "Ursula",
  },
  {
    id: 32,
    nom: "Charlie Chaplin",
    indice_1: "Acteur",
    indice_2: "The Tramp",
    indice_3: "Cinéma muet",
    indice_4: "Chapeau melon",
    indice_5: "Humanité",
  },
];
